enableAES: false
replicaCount: 1
service:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: mqtt-adapter
      port: 1883
      targetPort: 1883
    - name: http-adapter
      port: 18080
      targetPort: 18080
    - name: device-registry
      port: 28080
      targetPort: 28080
    - name: dispatch-router
      port: 5671
      targetPort: 15671
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: jaeger
      port: 16686
      targetPort: 16686
    - name: prometheus
      port: 9090
      targetPort: 9090
  annotations:
    getambassador.io/config: |
      ---  
      apiVersion: getambassador.io/v2
      kind:  TCPMapping
      metadata:
        name: hono-http-adapter
      spec:
        port: 18080
        service: hono-adapter-http-vertx:8080
      ---
      apiVersion: getambassador.io/v2
      kind: TCPMapping
      metadata:
        name: hono-mqtt-adapter
      spec:
        port: 1883
        service: hono-adapter-mqtt-vertx:1883
      ---
      apiVersion: getambassador.io/v2
      kind: TCPMapping
      metadata:
        name: hono-device-registry
      spec:
        port: 28080
        service: hono-service-device-registry-ext:28080
      ---
      apiVersion: getambassador.io/v2
      kind: TCPMapping
      metadata:
        name: hono-dispatch-router
      spec:
        port: 15671
        service: hono-service-device-registry-ext:15671
      ---
      apiVersion: getambassador.io/v2
      kind: TCPMapping
      metadata:
        name: prometheus-grafana
      spec:
        port: 3000
        prefix: /grafana/
        host: ms-k8stest.westeurope.cloudapp.azure.com
        service: prometheus-grafana:3000
      ---
      apiVersion: getambassador.io/v2
      kind: TCPMapping
      metadata:
        name: jaeger-operator-jaeger-query
      spec:
        port: 16686
        prefix: /jaeger/
        host: ms-k8stest.westeurope.cloudapp.azure.com
        service: jaeger-operator-jaeger-query:16686
      ---
      apiVersion: getambassador.io/v2
      kind: Mapping
      metadata:
        name: acme-challenge-mapping
      spec:
        prefix: /.well-known/acme-challenge/
        rewrite: ""
        service: acme-challenge-service
